[package]
name = "hc_zome_rea_proposed_to_integrity"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>", "Wesley <wesleyfinck@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdi = "=0.2.0"

hc_zome_rea_proposed_to_storage = { path = "../storage" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
