[package]
name = "hc_zome_rea_agent_index_agent"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.144"

hdk_semantic_indexes_zome_lib = { path = "../../../lib/hdk_semantic_indexes/zome" }
hdk_semantic_indexes_core = { path = "../../../lib/hdk_indexing_core" }
hdk_semantic_indexes_zome_derive = { path = "../../../lib/hdk_semantic_indexes/zome_derive" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_agent_rpc = { path = "../rpc" }
hc_zome_rea_agent_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
