[package]
name = "hc_zome_rea_economic_event_beef"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.119"

hc_zome_rea_economic_event_defs = { path = "../../../../../lib/rea_economic_event/defs" }
hc_zome_rea_economic_event_lib = { path = "../../../../../lib/rea_economic_event/lib" }
hc_zome_rea_economic_event_rpc = { path = "../../../../../lib/rea_economic_event/rpc" }
hc_zome_rea_economic_resource_rpc = { path = "../../../../../lib/rea_economic_resource/rpc" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
