[package]
name = "hc_zome_rea_agent_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>", "Wesley <wesleyfinck@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "=0.1.0"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_agent_rpc = { path = "../rpc" }
hc_zome_rea_agent_storage_consts = { path = "../storage_consts" }
hc_zome_dna_auth_resolver_core = {git = "https://github.com/holochain-open-dev/dna-auth-resolver", tag = "0.1.2", package = "hc_zome_dna_auth_resolver_lib"}


[lib]
crate-type = ["lib"]
