[package]
name = "hc_zome_rea_fulfillment"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1.0.104"
serde_json = { version = "1.0.47", features = ["preserve_order"] }
serde_derive = "1.0.104"
# :DUPE: hdk-rust-revid
hdk = "=0.0.48-alpha1"
hdk_proc_macros = "=0.0.48-alpha1"

hc_zome_rea_fulfillment_defs = { path = "../../../../../lib/rea_fulfillment/defs" }
hc_zome_rea_fulfillment_rpc = { path = "../../../../../lib/rea_fulfillment/rpc" }
hc_zome_rea_fulfillment_lib_origin = { path = "../../../../../lib/rea_fulfillment/lib_origin" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
