[package]
name = "hc_zome_rea_resource_specification"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.144"

hc_zome_rea_resource_specification_rpc = { path = "../rpc" }
hc_zome_rea_resource_specification_lib = { path = "../lib" }
hc_zome_rea_resource_specification_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
