[package]
name = "hc_zome_rea_proposed_intent"
version = "0.1.0"
authors = ["JhonatanHern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.123"

hc_zome_rea_proposed_intent_rpc = { path = "../rpc" }
hc_zome_rea_proposed_intent_lib = { path = "../lib" }
hc_zome_rea_proposed_intent_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
