[package]
name = "hc_zome_rea_unit_integrity"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>", "Wesley <wesleyfinck@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdi = "0.0.16"

hc_zome_rea_unit_storage = { path = "../storage" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
