#---------[ agents ]-----------

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScIxNpyVQrfbe6v75KgIrnRwftywuk3e6GkbxytTufworeYHtTo6OXX7i4q4a"
key_file = "../keyfile.txt"

#---------[ hApps ]-----------

[[dnas]]
file = "./holo-rea-dht/dist/holo-rea-dht.dna.json"
hash = ""
id = "HoloREA dev"

#---------[ gateway interfaces ]-----------

[[interfaces]]
admin = true
id = "http interface"
instances = []
[interfaces.driver]
type = "http"
port = 4000

[[interfaces]]
admin = true
id = "websocket interface"
instances = []
[interfaces.driver]
type = "websocket"
port = 3000

#---------[ misc ]-----------

[logger]
type = "debug"
