[package]
name = "hc_zome_rea_agent_rpc"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
holochain_serialized_bytes = "0.0.51"
hdk = "=0.0.147"

serde_maybe_undefined = { path = "../../../lib/serde_maybe_undefined" }
hdk_uuid_types = { path = "../../../lib/hdk_uuid_types" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }

[lib]
crate-type = ["lib"]
