[package]
name = "hc_zome_rea_economic_resource"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "=0.0.151"

hc_zome_rea_economic_resource_zome_api = { path = "../zome_api" }
hc_zome_rea_economic_resource_lib = { path = "../lib" }
hc_zome_rea_economic_resource_rpc = { path = "../rpc" }
hc_zome_rea_economic_resource_storage = { path = "../storage" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
