[package]
name = "hc_zome_rea_fulfillment_lib_destination"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
paste = "1.0"
# :TODO: remove if removing debug logging
# :DUPE: hdk-rust-revid
hdk = "0.0.147"

hdk_records = { path = "../../../lib/hdk_records" }
hdk_semantic_indexes_client_lib = { path = "../../../lib/hdk_semantic_indexes/client" }
hc_zome_rea_fulfillment_storage = { path = "../storage" }
hc_zome_rea_fulfillment_rpc = { path = "../rpc" }
hc_zome_rea_fulfillment_lib = { path = "../lib" }


[lib]
crate-type = ["lib"]
