[package]
name = "hc_zome_rea_economic_event_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "=0.0.151"

hdk_records = { path = "../../../lib/hdk_records" }
vf_actions = { path = "../../../lib/vf_actions" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
vf_measurement = { path = "../../../lib/vf_measurement" }
hc_zome_rea_economic_event_rpc = { path = "../rpc" }
hc_zome_dna_auth_resolver_core = {git = "https://github.com/holochain-open-dev/dna-auth-resolver", rev = "383ca3b", package = "hc_zome_dna_auth_resolver_lib"}


[lib]
crate-type = ["lib"]
