[package]
name = "hc_zome_rea_proposal_storage"
version = "0.1.0"
authors = ["Jhonatan Hern <JhonatanHern@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "=0.0.152"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_proposal_rpc = { path = "../rpc" }
hc_zome_dna_auth_resolver_core = {git = "https://github.com/holochain-open-dev/dna-auth-resolver", rev = "812840c", package = "hc_zome_dna_auth_resolver_lib"}


[lib]
crate-type = ["lib"]
