[package]
name = "hc_zome_rea_commitment"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "=0.0.152"

hc_zome_rea_commitment_rpc = { path = "../rpc" }
hc_zome_rea_commitment_lib = { path = "../lib" }
hc_zome_rea_commitment_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
