[package]
name = "hc_zome_rea_unit"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.112"

hc_zome_rea_unit_rpc = { path = "../rpc" }
hc_zome_rea_unit_lib = { path = "../lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
