[package]
name = "hc_zome_rea_process"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.112"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_process_rpc = { path = "../rpc" }
hc_zome_rea_process_lib = { path = "../lib" }
hc_zome_rea_commitment_storage_consts = { path = "../../rea_commitment/storage_consts" }
hc_zome_rea_intent_storage_consts = { path = "../../rea_intent/storage_consts" }
hc_zome_rea_economic_event_storage_consts = { path = "../../rea_economic_event/storage_consts" }
hc_zome_rea_process_storage_consts = { path = "../../rea_process/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
