[package]
name = "hc_zome_rea_resource_specification_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_resource_specification_rpc = { path = "../rpc" }

[lib]
crate-type = ["lib"]
