[package]
name = "hc_zome_rea_intent"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.119"

hc_zome_rea_intent_rpc = { path = "../rpc" }
hc_zome_rea_intent_lib = { path = "../lib" }
hc_zome_rea_intent_storage = { path = "../storage" }
hc_zome_rea_intent_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
