[package]
name = "hc_zome_rea_proposed_to_index_proposal"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "=0.1.0"

hdk_semantic_indexes_zome_lib = { path = "../../../lib/hdk_semantic_indexes/zome" }
hdk_semantic_indexes_core = { path = "../../../lib/hdk_semantic_indexes/integrity_core" }
hdk_semantic_indexes_zome_derive = { path = "../../../lib/hdk_semantic_indexes/zome_derive" }
hc_zome_rea_proposed_to_rpc = { path = "../rpc" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
