[package]
name = "hc_zome_rea_satisfaction_lib_origin"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
paste = "1.0"
hdk = "0.0"

hdk_records = { path = "../../../lib/hdk_records" }
hdk_semantic_indexes_client_lib = { path = "../../../lib/hdk_semantic_indexes/client" }
hc_zome_rea_satisfaction_storage_consts = { path = "../storage_consts" }
hc_zome_rea_satisfaction_storage = { path = "../storage" }
hc_zome_rea_satisfaction_rpc = { path = "../rpc" }
hc_zome_rea_satisfaction_lib = { path = "../lib" }

hc_zome_rea_commitment_rpc = { path = "../../rea_commitment/rpc" }

[lib]
crate-type = ["lib"]
