[package]
name = "hc_zome_rea_actions"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "0.0.115"

vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
vf_actions = { path = "../../../lib/vf_actions" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
