[package]
name = "hc_zome_rea_economic_event"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.112"

hc_zome_rea_economic_event_lib = { path = "../lib" }
hc_zome_rea_economic_event_rpc = { path = "../rpc" }
hc_zome_rea_economic_event_storage = { path = "../storage" }
hc_zome_rea_economic_resource_rpc = { path = "../../rea_economic_resource/rpc" }
hc_zome_rea_economic_resource_storage_consts = { path = "../../rea_economic_resource/storage_consts" }
hc_zome_rea_process_storage_consts = { path = "../../rea_process/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
