[package]
name = "hc_zome_rea_process"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
# :DUPE: hdk-rust-revid
hdk = "=0.0.42-alpha5"
hdk_proc_macros = "0.0.42-alpha5"

hdk_graph_helpers = { path = "../../../../../lib/hdk_graph_helpers" }
vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_process_defs = { path = "../../../../../lib/rea_process/defs" }
hc_zome_rea_process_storage_consts = { path = "../../../../../lib/rea_process/storage_consts" }
hc_zome_rea_process_storage = { path = "../../../../../lib/rea_process/storage" }
hc_zome_rea_process_rpc = { path = "../../../../../lib/rea_process/rpc" }
hc_zome_rea_process_lib = { path = "../../../../../lib/rea_process/lib" }
hc_zome_rea_commitment_storage_consts = { path = "../../../../../lib/rea_commitment/storage_consts" }
hc_zome_rea_intent_storage_consts = { path = "../../../../../lib/rea_intent/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
