[package]
name = "hc_zome_rea_proposed_to_rpc"
version = "0.1.0"
authors = ["Jhonatan Hern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
holochain_serialized_bytes = "0.0.51"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }

[lib]
crate-type = ["lib"]
