[package]
name = "hc_zome_rea_satisfaction_observation"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "=0.0.147"

hc_zome_rea_satisfaction_lib_destination = { path = "../lib_destination" }
hc_zome_rea_satisfaction_rpc = { path = "../rpc" }
hc_zome_rea_satisfaction_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
