[package]
name = "beef_industry_resource_specification"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1.0.104"
serde_json = { version = "1.0.47", features = ["preserve_order"] }
# :DUPE: hdk-rust-revid
hdk = "=0.0.49-alpha1"
hdk_proc_macros = "=0.0.49-alpha1"

hc_zome_rea_resource_specification_defs = { path = "../../../../../lib/rea_resource_specification/defs" }
hc_zome_rea_resource_specification_rpc = { path = "../../../../../lib/rea_resource_specification/rpc" }
hc_zome_rea_resource_specification_lib = { path = "../../../../../lib/rea_resource_specification/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
