[package]
name = "hc_zome_indexing_integrity_plan"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>", "Wesley <wesleyfinck@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdi = "=0.1.1"

hdk_semantic_indexes_core = { path = "../../../lib/hdk_indexing_core" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
