[package]
name = "hc_zome_rea_agent"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>", "Wesley <wesleyfinck@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.148"

hc_zome_rea_agent_rpc = { path = "../rpc" }
hc_zome_rea_agent_lib = { path = "../lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
