[package]
name = "hc_zome_rea_commitment_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "0.0.147"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
vf_measurement = { path = "../../../lib/vf_measurement" }
vf_actions = { path = "../../../lib/vf_actions" }
hc_zome_rea_commitment_rpc = { path = "../rpc" }
hc_zome_dna_auth_resolver_core = {git = "https://github.com/weswalla/dna-auth-resolver", package = "hc_zome_dna_auth_resolver_core"}


[lib]
crate-type = ["lib"]
