[package]
name = "hc_zome_rea_plan_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>", "Wesley <wesleyfinck@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "=0.0.147"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_plan_rpc = { path = "../rpc" }
hc_zome_rea_plan_storage_consts = { path = "../storage_consts" }
hc_zome_dna_auth_resolver_core = {git = "https://github.com/holochain-open-dev/dna-auth-resolver", rev = "d0de3d0", package = "hc_zome_dna_auth_resolver_core"}


[lib]
crate-type = ["lib"]
