[package]
name = "hc_zome_rea_actions"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1.0.104"
serde_json = { version = "1.0.47", features = ["preserve_order"] }
hdk = "=0.0.48-alpha1"
hdk_proc_macros = "=0.0.48-alpha1"

vf_actions = { path = "../../../../../lib/vf_actions" }
vf_core = { path = "../../../../../lib/vf_core" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
