[package]
name = "hc_zome_rea_satisfaction_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
hdk = "=0.1.0-beta-rc.1"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
vf_measurement = { path = "../../../lib/vf_measurement" }
hc_zome_rea_satisfaction_rpc = { path = "../rpc" }
hc_zome_dna_auth_resolver_core = {git = "https://github.com/holochain-open-dev/dna-auth-resolver", branch = "beta-rc", package = "hc_zome_dna_auth_resolver_lib"}


[lib]
crate-type = ["lib"]
