[package]
name = "hc_zome_rea_unit"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1.0.104"
serde_json = { version = "1.0.47", features = ["preserve_order"] }
serde_derive = "1.0.104"
# :DUPE: hdk-rust-revid
hdk = "=0.0.48-alpha1"
hdk_proc_macros = "=0.0.48-alpha1"

vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_unit_defs = { path = "../../../../../lib/rea_unit/defs" }
hc_zome_rea_unit_rpc = { path = "../../../../../lib/rea_unit/rpc" }
hc_zome_rea_unit_lib = { path = "../../../../../lib/rea_unit/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
