[package]
name = "hc_zome_rea_proposed_to"
version = "0.1.0"
authors = ["Jhonatan Hern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
# :DUPE: hdk-rust-revid
hdk = "=0.0.42-alpha5"
hdk_proc_macros = "=0.0.42-alpha5"

# hdk_graph_helpers = { path = "../../../../../lib/hdk_graph_helpers" }

vf_core = { path = "../../../../../lib/vf_core" }
hc_zome_rea_proposed_to_storage_consts = { path = "../../../../../lib/rea_proposed_to/storage_consts" }
hc_zome_rea_proposed_to_defs = { path = "../../../../../lib/rea_proposed_to/defs" }
hc_zome_rea_proposed_to_rpc = { path = "../../../../../lib/rea_proposed_to/rpc" }
hc_zome_rea_proposed_to_lib = { path = "../../../../../lib/rea_proposed_to/lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
